name: madkour_task
description: A Flutter position task for Madkour Co.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/logo.jpeg
  color: "#ffffff"
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

    - family: Teko
      fonts:
        - asset: assets/fonts/Teko-Light.ttf
          weight: 300
        - asset: assets/fonts/Teko-Regular.ttf
          weight: 400
        - asset: assets/fonts/Teko-Medium.ttf
          weight: 500
        - asset: assets/fonts/Teko-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Teko-Bold.ttf
          weight: 700

    - family: StickNoBills
      fonts:
        - asset: assets/fonts/StickNoBills-Light.ttf
          weight: 300
        - asset: assets/fonts/StickNoBills-Regular.ttf
          weight: 400
        - asset: assets/fonts/StickNoBills-Medium.ttf
          weight: 500
        - asset: assets/fonts/StickNoBills-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/StickNoBills-Bold.ttf
          weight: 700
